<?php

function wagam_dashboard_preprocess_form_element(&$variables){

  ///Gestion du champs image du profil.
  if(isset($variables['name']) && $variables['name'] == 'user_picture[0]'){
    $variables['label_display'] = false;
    $variables['description_display'] = 'before';
    if(empty($variables['element']['#value']['fids'])){
      $variables['description_display'] = 'invisible';
      $variables['suffix'] = [
        '#type' => 'html_tag',
        '#tag' => 'button',
        '#attributes' => [
          'type' => 'button',
          'id' => 'change-default-img',
          'class' => [
            'btn',
            'btn-secondary',
          ]
        ],
      ];
      $variables['suffix']['label'] = [
        '#markup' => '<i class="far fa-edit"></i> Modifier mon image',
      ];
    }
  }
}

function wagam_dashboard_preprocess_image_widget(&$variables){
  $image_style_storage = \Drupal::entityTypeManager()->getStorage('image_style');
  $media_storage = \Drupal::entityTypeManager()->getStorage('media');
  $image_style_large = $image_style_storage->load('large');

  if(!empty($variables['data']['fids']['#value'])){
    unset($variables['data']['file_'.$variables['data']['fids']['#value'][0]]);
  }else{
    $config = \Drupal::config('wagam.general.config');
    $user_config = $config->get('user');
    if(!empty($user_config) && isset($user_config['default_user_picture'])){
      $media = $media_storage->load($user_config['default_user_picture']);

      $variables['data']['default_image_wrapper'] = [
        '#type' => 'container',
        '#attributes' => [
          'class' => [
            'image-preview'
          ]
        ]
      ];
      $variables['data']['default_image_wrapper']['default_image'] = [
        '#type' => 'html_tag',
        '#tag' => 'img',
        '#attributes' => [
          'class' => [
            'rounded',
            'default-img',
          ],
          'src' => $image_style_large->buildUrl($media->get('field_media_image')->entity->uri->getString()),
        ]
      ];

      $variables['data']['upload']['#attributes']['class'][] = 'd-none';

      $variables['#attached']['library'][] = 'wagam_dashboard/wagam_dasboard.image-preview-widget';
    }
  }

  $variables['data']['remove_button']['#value'] = t('Modifier mon image');
  if(isset($variables['data']['preview'])){
    $variables['data']['preview'] = [
      '#type' => 'html_tag',
      '#tag' => 'img',
      '#attributes' => [
        'src' => $image_style_large->buildUrl($variables['data']['preview']['#uri']),
        'class' => 'rounded',
      ],
    ];
  }
}
