<?php

function wagam_blocks_preprocess_menu(&$variables)
{
  if($variables['menu_name'] === 'account')
  {
    $block_manager = \Drupal::service('plugin.manager.block');
    $plugin_block = $block_manager->createInstance('wagam_account_block', []);
    // Some blocks might implement access check.
    // Return empty render array if user doesn't have access.
    $render = $plugin_block->build();

    // Add the cache tags/contexts.
    \Drupal::service('renderer')->addCacheableDependency($render, $plugin_block);
    $variables['items']['menu.my_account']['account_block'] = $render;
  }
}
